name: Backport changes to maintenance branches
on:
 push:
  branches:
   - main

env:
  MAINTENANCE_BRANCHES: "['5.3', '5.4', '5.5']"

jobs:

  backport-to-all-branch:
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(env.MAINTENANCE_BRANCHES) }}
    uses: ./.github/workflows/backport-workflow.yml
    with:
      label-to-check-for: '["backport to all versions"]'
      target-branch: v/${{ matrix.branch }}
    secrets: inherit

  backport-to-specified-branch:
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(env.MAINTENANCE_BRANCHES) }}
    uses: ./.github/workflows/backport-workflow.yml
    with:
      label-to-check-for: '["backport to ${{ matrix.branch }}"]'
      target-branch: v/${{ matrix.branch }}
    secrets: inherit
