# This workflow takes the contents of the branches/tags and builds the production documentation site

name: Build production site

on:
  push:
    branches: [ main, 'v/*' ]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger docs deployment
      uses: ./.github/actions/deploy
