# This workflow takes the contents of the branches/tags and builds the production documentation site

name: Build production site

on:
  push:
    branches: [ main, 'v/*' ]

jobs:
  dispatch:
    uses: ./.github/workflows/deploy-docs-workflow.yml
