name: Deploy docs
description: Dispatch Netlify production deployment

on:
  workflow_call:

jobs:
  dispatch-deploy:
    runs-on: ubicloud-standard-2
    steps:
      - name: Dispatch docs deployment
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/60e71936b15bb431b42b698a
